/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Oct 08 14:03:42 CST 2016
 */
package com.bosssoft.egov.aims.api;

import java.util.List;

import com.bosssoft.egov.aims.model.TPerson;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.entity.Searcher;



/**
 * Service类接口 .
 * 
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-10-08   Administrator　　　新建
 * </pre>
 */
public interface TPersonService {

/**
	 * 增加.
	 * 
	 * @param tPerson 
	 */
	public void addTPerson(TPerson tPerson);

	/**
	 * 删除及相关信息.
	 * 
	 * @param tPerson 
	 */
	public void delTPerson(TPerson tPerson);

	/**
	 * 修改.
	 * 
	 * @param tPerson 
	 */
	public void updateTPerson(TPerson tPerson);

	/**
	 * 获取列表.
	 * 
	 */
	public List<TPerson> getTPersonList(TPerson tPerson);




   	/**
	 * 获取分页.
	 * 
		 */
	public Page<TPerson> queryTPersonPage(Searcher searcher, Page<?> pageInfo);
			
    
}
 