/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Oct 08 14:05:11 CST 2016
 */
package com.bosssoft.egov.aims.mapper;

import org.apache.ibatis.annotations.Param;

import com.bosssoft.egov.aims.model.TPerson;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.common.Mapper;
import com.bosssoft.platform.persistence.entity.Searcher;
import com.bosssoft.platform.runtime.BossException;

/**
 * 类说明:  Mapper接口（ Mapper层） .
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-10-08   Administrator　　　新建
 * </pre>

 */

public interface TPersonMapper extends Mapper<TPerson>{



/**
	 * 
	 * 查询分页.
	 *	`
	 * @param searcher 查询条件
	 * @param pageable 分页信息
	 * @return TPersonPage列表
	 * @throws BusinessException 自定义异常
	 *
	 */
	public Page<TPerson> queryTPersonPage(@Param("searcher")Searcher searcher,@Param("page")Page<?> pageInfo)
			throws BossException;


}