/**
 * * Auto generated by Bossssoft Studio version 1.0 beta Sun Sep 18 11:47:10 CST
 * 2016
 */
// define(['引入外部js模块或控件'],function('引入外部js或控件的别名'){})
define(
		[ "app/widgets/window/app-dialog", "app/app-pagebase" ],
		function(Dialog, PageBase) {
			var AfaApplicationDlg = PageBase
					.extend({
						// 类初始化
						initialize : function() {
							AfaApplicationDlg.superclass.initialize.call(this);
						},
						ACTION : {
							ADD : "ADD",
							EDIT : "EDIT",
							VIEW : "VIEW"
						},
						// 存储弹出窗口回调
						showPageCallBack : null,
						// 当前窗口状态
						indexAction : null,
						// 控件监听事件 格式：#控件id#:{事件名:事件方法}
						listeners : {
							// 新增并保存
							afaApplicationPage_saveaddBtn : {
								click : function() {
									var self = AfaApplicationDlg.getInstance();
									self.doSave({
										isSaveAdd : true
									})
								}
							},
							// 新增
							afaApplicationPage_addBtn : {
								click : function() {
									$A("#afaApplicationPage_form")
											.clearFormEditorValue();
								}
							},
							// 编辑
							afaApplicationPage_editorBtn : {
								click : function() {
									var self = AfaApplicationDlg.getInstance();
									self.indexAction = self.ACTION.EDIT;
									$A("#afaApplicationPage_editorBtn").hide();
									$A("#afaApplicationPage_saveBtn").show();
									$A("#afaApplicationPage_form")
											.toggleFormState("edit");
									$A("#appId").textbox("readonly", false);
									$A("#appName").textbox("readonly", false);
									$A("#appType").textbox("readonly", false);
									$A("#isOpen").textbox("readonly", false);
									$A("#context").textbox("readonly", false);
									$A("#ip").textbox("readonly", false);
									$A("#port").textbox("readonly", false);
									$A("#protocol").textbox("readonly", false);
									$A("#appDesc").textbox("readonly", false);
									$A("#tenantId").textbox("readonly", false);
								}
							},
							// 保存
							afaApplicationPage_saveBtn : {
								click : function() {
									var self = AfaApplicationDlg.getInstance();
									self.doSave({
										isSaveClose : true
									})
								}
							},
							// 关闭
							afaApplicationPage_closeBtn : {
								click : function() {
									$.closeDialog();
								}
							}
						},
						loadData : function(param, callback) {
							var url = "platform/appframe/controller/afaapplication/getAfaApplication.do"
							$.ajaxCall({
								url : url,
								data : param,
								callback : function(data) {
									$A("#afaApplicationPage_form")
											.refreshFormData(data);
									if (callback) {
										callback();
									}
								}
							})
						},
						// 保存数据cofig:{isSaveAdd:"保存并新增",isSaveClose:"保存关闭",isSaveView:"保存查看"}可自行扩展
						doSave : function(config, callback) {
							var url = "";
							if (this.indexAction == this.ACTION.ADD) {
								url = "platform/appframe/afaapplication/doInsert.do"
							}
							if (this.indexAction == this.ACTION.EDIT) {
								url = "platform/appframe/afaapplication/doUpdate.do"
							}
							var _self = AfaApplicationDlg.getInstance();
							$A('#afaApplicationPage_form')
									.sumbitAllComp(
											{
												submitMode : 'all',
												url : url,
												callback : function(json) {
													if (config.isSaveAdd) {
														$A(
																"#afaApplicationPage_form")
																.clearFormEditorValue();
														_self.indexAction = _self.ACTION.ADD;
													} else if (config.isSaveClose) {
														$.closeDialog();
														_self.indexAction = "";
													} else if (config.isSaveView) {
														$A(
																"#afaApplicationPage_form")
																.toggleFormState(
																		"view");
														$A("#appId").textbox(
																"readonly",
																true);
														$A("#appName").textbox(
																"readonly",
																true);
														$A("#appType").textbox(
																"readonly",
																true);
														$A("#isOpen").textbox(
																"readonly",
																true);
														$A("#context").textbox(
																"readonly",
																true);
														$A("#ip").textbox(
																"readonly",
																true);
														$A("#port").textbox(
																"readonly",
																true);
														$A("#protocol")
																.textbox(
																		"readonly",
																		true);
														$A("#appDesc").textbox(
																"readonly",
																true);
														$A("#tenantId")
																.textbox(
																		"readonly",
																		true);
														_self.indexAction = _self.ACTION.VIEW;
													}
													if (_self.showPageCallBack) {
														_self
																.showPageCallBack();
													}
												}
											});
						},
						// 显示弹出窗口，action
						// 窗口状态来源，ACTION:{ADD:"",EDIT:"",VIEW:""}//可自行扩展
						showPage : function(action, data, callback) {
							this.showPageCallBack = callback || function() {
							};
							var self = this;

							this.indexAction = action;
							var options = {
								url : "platform/appframe/afaapplication/showAdd.do",
								dialogId : "directPayBookAdd",
								title : "新增",
								width : 800,
								height : 600,
								wrapper : true,
								hasheader : false,
								reload : true,
								onPageLoad : function(obj) {
									if (self.indexAction == self.ACTION.ADD) {
										$A("#afaApplicationPage_editorBtn")
												.hide();
										$A("#afaApplicationPage_addBtn").hide();
										$A(".dlg-box-head-title").html("新增");
									}
									if (self.indexAction == self.ACTION.EDIT) {
										$A("#afaApplicationPage_addBtn").hide()
										$A("#afaApplicationPage_saveaddBtn")
												.hide();
										$A("#afaApplicationPage_editorBtn")
												.hide();
										$A(".dlg-box-head-title").html("修改");
										$A("#afaApplicationPage_form")
												.refreshFormData(data);
									}
									if (self.indexAction == self.ACTION.VIEW) {
										$A("#afaApplicationPage_addBtn").hide()
										$A("#afaApplicationPage_saveaddBtn")
												.hide();
										$A("#afaApplicationPage_saveBtn")
												.hide();
										$A(".dlg-box-head-title").html("查看");
										$A("#afaApplicationPage_form")
												.refreshFormData(data);
										$A("#afaApplicationPage_form")
												.toggleFormState("view");
										$A("#appId").textbox("readonly", true);
										$A("#appName")
												.textbox("readonly", true);
										$A("#appType")
												.textbox("readonly", true);
										$A("#isOpen").textbox("readonly", true);
										$A("#context")
												.textbox("readonly", true);
										$A("#ip").textbox("readonly", true);
										$A("#port").textbox("readonly", true);
										$A("#protocol").textbox("readonly",
												true);
										$A("#appDesc")
												.textbox("readonly", true);
										$A("#tenantId").textbox("readonly",
												true);
									}
								}
							};
							$.openModalDialog(options)

						},
						// 页面加载后初始化
						initPage : function() {

						},
						// 控件属性重置
						initUIExtConfig : function() {
							this.uiExtConfig = {
							// 格式 #控件id#:function(控件属性集类){
							// config.setAttr("控件属性名","属性值"),//
							// 网格，下拉网格，特殊设置config.getColumn("网列id").setAttr("列属性名","列属性值")config.getButton("网格内包含的按钮id").setAttr("handler","点击事件")
							// }

							}
						}

					});
			// 创建窗体类单例
			AfaApplicationDlg.getInstance = function() {
				if (!this.instance) {
					this.instance = new AfaApplicationDlg();
				}
				return this.instance;
			}

			return AfaApplicationDlg.getInstance();
		})