/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Oct 08 14:06:33 CST 2016
 */
package com.bosssoft.egov.aims.controller;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import com.bosssoft.egov.aims.api.TPersonService;
import com.bosssoft.egov.aims.model.TPerson;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.entity.Searcher;

@Controller
@RequestMapping("egov/aims/tperson")
public class TPersonController {

	@Autowired
	private TPersonService tPersonService;

  /**
     * 列表页面
	 */
    @RequestMapping(value = "showIndex.do")
    public String showIndex() {
        return "egov/aims/tperson/tperson_index.ui";
    }
    
     /**
     * 新增页面
	 */
    @RequestMapping(value = "showAdd.do")
    public String showAdd() {
        return "egov/aims/tperson/tperson_add.ui";
    }
    
   /**
     * 新增
     * @param tPerson 新增信息
	 */
    @RequestMapping(value = "doInsert.do",method=RequestMethod.POST)
    @ResponseBody
    public void doInsert(TPerson tPerson)  {
      	tPersonService.addTPerson(tPerson);
    }
    
   /**
     * 修改
     * @param tPerson 修改信息
	 */
    @RequestMapping(value = "doUpdate.do", method = RequestMethod.POST)
    @ResponseBody
    public void doUpdate(TPerson tPerson)  {
		tPersonService.updateTPerson(tPerson);
    }
    
 /**
     * 删除
     * @param tPerson 删除条件
	 */
	 @RequestMapping(value = "doDelete.do", method = RequestMethod.POST)
	 @ResponseBody
	 public void doDelete(TPerson tPerson)  {
		tPersonService.delTPerson(tPerson);
	 }
	   /**
     * 获取单条记录
     * @param  tPerson 条件
	 */
	 @RequestMapping(value=" getTPerson")
	 @ResponseBody
	 public TPerson getTPerson(TPerson tPerson) {
		return null;
	}
	 
	  /**
     * 获取列表
     * @param  tPerson 条件
	 */
	 @RequestMapping(value=" getTPersonList")
	 @ResponseBody
	 public List<TPerson> getTPersonList(TPerson tPerson) {
		return null;
	}
	 /**
     * 获取分页
     * @param searcher 查询条件
     * @param page 分页信息
	 */
	 @RequestMapping(value="queryTPersonPage.do")
	 @ResponseBody
	 public  Page<TPerson> queryTPersonPage(Searcher searcher, Page<?> pageInfo) {
		 return tPersonService.queryTPersonPage(searcher, pageInfo);

	}
}