
/**
 * 福建博思软件 1997-2016 版权所有
 * Auto generated by Bosssoft Studio version 1.0 beta
 * Sat Oct 08 14:05:47 CST 2016
 */
package com.bosssoft.egov.aims.spi;

import java.util.List;
import com.bosssoft.egov.aims.model.TPerson;
import com.bosssoft.platform.common.lang.data.Page;
import com.bosssoft.platform.persistence.entity.Searcher;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.bosssoft.egov.aims.api.TPersonService;
import com.bosssoft.egov.aims.mapper.TPersonMapper;
import com.bosssoft.platform.runtime.BossException;


/**
 * 类说明: TPersonService接口实现类. 
 *
 * 类用途：
 *
 * <pre>
 * 修改记录：
 * 修改日期　　　修改人　　　修改原因
 * 2016-10-08   Administrator　　　新建
 * </pre>
 */
@Service
public class TPersonServiceImpl implements TPersonService {

	private static Logger logger = LoggerFactory.getLogger(TPersonServiceImpl.class);

	// TODO 添加需要的Mapper
	@Autowired
	private TPersonMapper tPersonMapper;
	
	/**
	 *
	 * @param tPerson
	 * @
	 */
	public void addTPerson(TPerson tPerson)  {
		tPersonMapper.insert(tPerson);
	}

	/**
	 *
	 * @param tPerson
	 * @
	 */
	public void delTPerson(TPerson tPerson)  {
		tPersonMapper.deleteByPrimaryKey(tPerson);
	}

	/**
	 *
	 * @param tPerson
	 * @
	 */
	public void updateTPerson(TPerson tPerson)  {
		tPersonMapper.updateByPrimaryKey(tPerson);
	}

	/**
	 *
	 * @param tPerson
	 * @retrun
	 * @
	 */
	public List<TPerson> getTPersonList(TPerson tPerson)  {
		return null;
	}

	/**
	 *
	 * @param searcher
	 * @param pageInfo
	 * @retrun
	 * @
	 */
	public Page<TPerson> queryTPersonPage(Searcher searcher, Page<?> pageInfo)  {
		//return null;
		
		try {
			Page<TPerson> tp = tPersonMapper.queryTPersonPage(searcher, pageInfo);
			return tp;
		} catch (BossException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}